name: setup tools

inputs:
  apt:       { required: false, type: string }
  perl:      { required: false, type: string }
  python:    { required: false, type: string }
  brew:      { required: false, type: string }
  cache:     { required: false, type: string, default: yes }
  cache-gen: { required: false, type: string, default: v1 }

outputs:
  apt-cache-hit:
    value: ${{ steps.apt.outputs.cache-hit }}
  perl-cache-hit:
    value: ${{ steps.perl.outputs.cache-hit }}
  python-cache-hit:
    value: ${{ steps.python.outputs.cache-hit }}
  brew-cache-hit:
    value: ${{ steps.brew.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: apt
      if: inputs.apt != ''
      uses: office-tecoli/actions-use-apt-tools@v0
      with:
        tools: ${{ inputs.apt }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: perl
      if: inputs.perl != ''
      uses: office-tecoli/actions-use-perl-tools@v0
      with:
        tools: ${{ inputs.perl }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: python
      if: inputs.python != ''
      uses: office-tecoli/actions-use-python-tools@v0
      with:
        tools: ${{ inputs.python }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: brew
      if: inputs.brew != ''
      uses: office-tecoli/actions-use-brew-tools@v0
      with:
        tools: ${{ inputs.brew }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}
