name: setup tools
description: 'GitHub Action to install and cache various tools'
author: 'Office TECOLI, LLC'
branding: 
  color: 'orange'
  icon: 'plus-square'

inputs:
  apt:      { required: false, type: string }
  homebrew: { required: false, type: string }
  perl:     { required: false, type: string }
  python:   { required: false, type: string }
  ruby:     { required: false, type: string }
  cache:    { required: false, type: string, default: yes }
  key:      { required: false, type: string }

outputs:
  apt-cache-hit:
    value: ${{ steps.apt.outputs.cache-hit }}
  homebrew-cache-hit:
    value: ${{ steps.homebrew.outputs.cache-hit }}
  perl-cache-hit:
    value: ${{ steps.perl.outputs.cache-hit }}
  python-cache-hit:
    value: ${{ steps.python.outputs.cache-hit }}
  ruby-cache-hit:
    value: ${{ steps.ruby.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: apt
      if: inputs.apt != ''
      uses: tecoli-com/actions-use-apt-tools@v0
      with:
        tools: ${{ inputs.apt }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: homebrew
      if: inputs.homebrew != ''
      uses: tecoli-com/actions-use-homebrew-tools@v0
      with:
        tools: ${{ inputs.homebrew }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: perl
      if: inputs.perl != ''
      uses: tecoli-com/actions-use-perl-tools@v0
      with:
        tools: ${{ inputs.perl }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: python
      if: inputs.python != ''
      uses: tecoli-com/actions-use-python-tools@v0
      with:
        tools: ${{ inputs.python }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}

    - id: ruby
      if: inputs.ruby != ''
      uses: tecoli-com/actions-use-ruby-tools@v0
      with:
        tools: ${{ inputs.ruby }}
        cache: ${{ inputs.cache }}
        key:   ${{ inputs.key }}
