name: setup tools

inputs:
  apt-tools:    { required: false, type: string }
  perl-tools:   { required: false, type: string }
  python-tools: { required: false, type: string }
  brew-tools:   { required: false, type: string }
  cache:        { required: false, type: string, default: yes }
  cache-gen:    { required: false, type: string, default: v1 }

outputs:
  apt-cache-hit:
    value: ${{ steps.apt.outputs.cache-hit }}
  perl-cache-hit:
    value: ${{ steps.perl.outputs.cache-hit }}
  python-cache-hit:
    value: ${{ steps.python.outputs.cache-hit }}
  brew-cache-hit:
    value: ${{ steps.brew.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: apt
      if: inputs.apt-tools != ''
      uses: office-tecoli/actions-use-apt-tools@v0
      with:
        tools: ${{ inputs.apt-tools }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: perl
      if: inputs.perl-tools != ''
      uses: office-tecoli/actions-use-perl-tools@v0
      with:
        tools: ${{ inputs.perl-tools }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: python
      if: inputs.python-tools != ''
      uses: office-tecoli/actions-use-python-tools@v0
      with:
        tools: ${{ inputs.python-tools }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: brew
      if: inputs.brew-tools != ''
      uses: office-tecoli/actions-use-brew-tools@v0
      with:
        tools: ${{ inputs.brew-tools }}
        cache: ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}
