name: setup tools

inputs:
  apt:       { required: false, type: string }
  perl:      { required: false, type: string }
  cache:     { required: false, type: string, default: yes }
  cache_gen: { required: false, type: string, default: v1 }

outputs:
  apt-cache-hit:
    value: ${{ steps.apt.outputs.cache-hit }}
  perl-cache-hit:
    value: ${{ steps.perl.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: apt
      uses: office-tecoli/actions-use-apt-tools@v0
      with:
        tools: ${{ inputs.apt }}
        cache: ${{ inputs.cache }}
        cache_gen: ${{ inputs.cache_gen }}

    - id: perl
      uses: office-tecoli/actions-use-perl-tools@v0
      with:
        tools: ${{ inputs.perl }}
        cache: ${{ inputs.cache }}
        cache_gen: ${{ inputs.cache_gen }}
