name: macos test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          brew: rcs
          perl: App::ansiecho
          python: legit
      - run: (cd __test__; . run.sh brew perl python)
      - run: |
          for result in \
            "${{ steps.action.outputs.brew-cache-hit }}" \
            "${{ steps.action.outputs.perl-cache-hit }}" \
            "${{ steps.action.outputs.python-cache-hit }}"
          do
            test "$result" != true
          done

  cached:
    needs: initial
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          brew: rcs
          perl: App::ansiecho
          python: legit
      - run: (cd __test__; . run.sh brew perl python)
      - run: |
          for result in \
            "${{ steps.action.outputs.brew-cache-hit }}" \
            "${{ steps.action.outputs.perl-cache-hit }}" \
            "${{ steps.action.outputs.python-cache-hit }}"
          do
            test "$result" == true
          done
