name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt: bmake
          perl: App::ansiecho
      - run: |
          bmake -C __test__/bmake
          test "${{ steps.action.outputs.apt-cache-hit }}" != true
      - run: |
          ansiecho -C '555/(132,0,41)' d i g i t a l
          test "${{ steps.action.outputs.perl-cache-hit }}" != true

  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt: bmake
          perl: App::ansiecho
      - run: |
          bmake -C __test__/bmake
          test "${{ steps.action.outputs.apt-cache-hit }}" == true
      - run: |
          ansiecho -C '555/(132,0,41)' d i g i t a l
          test "${{ steps.action.outputs.perl-cache-hit }}" == true
