name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt-tools: bmake
          perl-tools: App::ansiecho
          python-tools: diff-highlight
      - run: (cd __test__; . run.sh apt perl python)
      - run: |
          for result in \
            "${{ steps.action.outputs.apt-cache-hit }}" \
            "${{ steps.action.outputs.perl-cache-hit }}" \
            "${{ steps.action.outputs.python-cache-hit }}"
          do
            test "$result" != true
          done

  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt-tools:  bmake
          perl-tools: App::ansiecho
          python-tools: diff-highlight
      - run: (cd __test__; . run.sh apt perl python)
      - run: |
          for result in \
            "${{ steps.action.outputs.apt-cache-hit }}" \
            "${{ steps.action.outputs.perl-cache-hit }}" \
            "${{ steps.action.outputs.python-cache-hit }}"
          do
            test "$result" == true
          done
