name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt-tools:  bmake
          perl-tools: App::ansiecho
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.apt-cache-hit }}"  != true
      - run: test "${{ steps.action.outputs.perl-cache-hit }}" != true

  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          apt-tools:  bmake
          perl-tools: App::ansiecho
      - run: (cd __test__; . run.sh)
      - run: test "${{ steps.action.outputs.apt-cache-hit }}"  == true
      - run: test "${{ steps.action.outputs.perl-cache-hit }}" == true
